language: python
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
python:
- '2.7'
addons:
  apt_packages:
  - pandoc
env:
  global:
  - PATH=$PATH:${HOME}/google-cloud-sdk/bin GAE_LIB_ROOT=${HOME}/google-cloud-sdk/platform/google_appengine
    CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: Z3sbrtcXTy3nbzw+WG1dqj9KfLM7ZBQhPRwxOZalypHpNpDTGBjfQgE6W/psaSoQFhCnois84Aad7/q6oP1C/RzF8tEv/Pqum/xSjvYsCfc78ZFyFg/Tn8hjdXdY04S0aLEAJQa0U+dTPweHoTjuC7jNViQi1G43ZsPsY/Ml63liescrA5ozOKpjrGWJknw8j8QSAis69G1hEGnxSbHt6zPcinjpCLwE6N93mnRPmehYv+ohjs4bntti5hspb5GNKLKnS9N+BURQpsaa0qaKzNhAhlEOHbgAD3+i1oNp5KvhWcascFYWYwVq2TPVNoMUG7zZ7uCsPmWxIS7XjiHGSFItdULeFu+DsRGqgL438zW1J3CD9kHf0nvIny8AxO8gaH7sd5H5v3DEK0lMHuPJ7BssY8kuDQmOmS/nYXLT/b1wvWsBei+DT2h0p9el/x3LK+sCMvlCDUzHvfhAP8ksmfujDzAcLlvchhHf0UmkVcidknO1qPw8v9ho4SRKl2PBWWn4fFDgestwrbxLMDeoVO+UT/HDHWeLaaVcZXvND1V5YH6FcpCW6kphlido2m++67MS80vajHLlvVdQ3eYRUjaiuy/WgYPoYkVOKSaqbsXiOdaab7Vue/ubn9iyA3//O8xsj+wchyBBFCcakgxkTNUosfN2iF+QfUvgFhMMyYM=
  - secure: VgjzqhfxLkUIveLCL0OYFa2os6BOPXIdL39Fz4/jVyCojXY4wifRso8BjY2gz6ZEqFbZ7FdnrPA3pR+ai4V63DXg/ne/bGZqT4KB4cxPQpTJt8aBTYLhxqdOOgzbW6lDdG381OwV3uwIL3mFnq3y+dB8fLJE1HPhPhyXQ5eT6rwoOnapC3fmnceKyCf8VBhW930oCEu9JqFLilS+Px2zT3UPAxq+jIb0mgipT0+SqOaxgB4av0mTfSTOVL/IYMU9v7yOLtVPXVMmE9/LrFCVX6xg4laqm8DRfd5+snVLje8FdnfMZwHHun8EepRCvTunJuuivFQ8BcqINSc+REmHrE9yyNt5J0QvqzJqDTkfJfkIpkpER8VDzJFrKfFv6ZQWwDGgskqX2vHFf+vrzd8DCptDbnSAqq10kFWJbUTYbApftcJTuje040584BskFtO6YIhuuhk1azl5t2Q8jD3yi0Y3wkCDD/jI9naYd4DJe7SZqJal5VcXzKkyTjhPf5Fu877GmQrkan8iNoRjwY/IFUNJeS0zkZQUctBnM4VDnNaq5OIn19Ctxx7AASMsUl/byowum7yfOKayHVN2/raGu9dAeiNGkMByZnR/mg1e828FGpJ5qoFJfmB+sjkdAU4UK5QrsfWJHe9BJJUFlldhuks4Q3Ng/s8x/d9F92tKaI0=
  - secure: g7PXmu+BBpVlooLE/WNtxnZ2OWuaqckMCVXYenbaTQs70tsifqMW5eqy+zzflQDQFTl77F8RXPSVWjTYdPUkUZ+v6jvw8cfDnwJ4nB+30Cy5NbSsSWwjVlh+0pbVX+tU5DKjHZewu3TA7gSp6sluQjGTgFGlF7p0Ly57MMJMaC2zfph0Co/0AexSISqGkHSujFzlAY40D8Lb2gPKhfAA5DuBSvBi1HfHB6r67B/qek0jqN0JguTjGEcbq3w3Bi7WmZ73x17sQsGwOR+AWoeR/Qu+o88ih7YRuYOxQeiERgPjKTw+lK8Amoaw0Iw41xz6hzfunfY+38qUNyy2IfuRY6PmNuaPCSU6Kd1upx75Xv0+N9xjH7/PmlhvYtxD/+Q+kW3P/QXYiaUDyyOgjczq39c7NzmIkLDWjyV4pQvkrkbJc26DtANflsFOKZcnPMYz2x+GVtbltYaC2ga/a4qeVt41yyI2tnvrlJxB5BeR3E9lTv2LMzxsuUvflJ85jdozSS5hmG+o+RMJMAJwwabrQENvHp5CVQKiG8Or9PW5J+H9GjYpOI/3C2dGfP8P73D5i49eCMCCZnuuMZhK+sYkroUsh9+tCZIPt3qjREVIzlLHegPMpVjAhRJSIlDxg+CQH5gzqFl8arfWW9u2IR3T444scxfPTfvf3GVs2O2pOvk=
before_install:
- if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then rm -rf ${HOME}/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash; gcloud --version; gcloud -q components
  install app-engine-python; fi
install:
- gcloud --version
- pip install --upgrade pip
- "./pip.sh"
script:
- "./tests.sh"
before_deploy: echo $TRAVIS_TAG
deploy:
  provider: pypi
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$"
after_success:
- git config --global user.name "python-semantic-release"
- git config --global user.email "development-public@gaincompliance.com"
- pip install python-semantic-release
- semantic-release publish
notifications:
  email: false
  slack:
    secure: VJfbgnzAwFlAITf3ER/4hVW1cA0XVkp5kAdqSETL2h4jU10PU/UFWB00X/SXIJZSM7XLcAO2hV9jIXnqKbfsDtosIJymC0qR4OX3CY3u+4NnEcWLEaQqJgtqRpa0Olrn6OHlb2Hek0Gl3xBzGuWxXLwqLaeeO9SYoWFcjphu6leC/CkvCIiaXp0rh/t0wixAGfPMhqlgyd08ew9PPJAhATjyDKZilP0hxMwJNkeA18tNJearYaGyY7oUqXYs01kEfEFAO66sHG64SBW0mH02sLiYvo7IGCWUEuvQVlqXtaB3/WOcN2lsQ9kAxaAFOiIutgoWcZ3Np2kMhZUJn0k0oOfb94io6hHr5fE0Kxqcppz04P+Z0iWMGOqgazAeC4SZKeIsnInDDcESOlf1pxPXEsmgtjISeAhdZYUp6QtKXdOnP74EbCheLBofVrAFplrsWvouGfcP2DOkPdPJz/X1YZk4+8toIhSnVA3412JI2px4tTld1ph3kncj+rYCvg3A0pO7ir2sICGPaUoYaoXxUpPzPtsfG9cqmDJ8zeLdOC9+vTQeOaiYx+/MlaPJBC3CvOIBRd2J8ynjexzk6B0p58ALyt6jx6A9lH0yciltD4LGrzkBItmEi25t77t9nY8qcto3TsaRqjmn4SG7jJCOIvyTV8kSKYV3PQUgDVh719Q=
